### PR TITLE
Add optional geolocation

### PR DESCRIPTION
**Pull request by a13**
Hi, thanks for a nice plugin!

As a person who travels a lot, I'd like to get my location info automatically. This patch allows getting that info from ipinfo.io server.

### CODE REVIEW

**Comment by lujun9972** [comment]
Thanks, it's a great patch.
Will it better if we combine the `yahoo-weather-location` and `yahoo-weather-guess-location-function`?
I mean  `yahoo-weather-location` could be a string or a function, and if it is a function, then it will be invoked to get the location.

**Comment by a13** [comment]
The thing is `yahoo-weather-guess-location-function` doesn't get the location directly, but just runs `url-retrieve` with a callback which _sets_ the `yahoo-weather-location` variable. To return the location directly, it should make `url-retrieve-synchronously` request, but I don't think it's a good idea. 

Any thoughts how to deal with that?

**Comment by a13** [comment]
Also, `yahoo-weather-location` serves as a backup location, until the request returns success. Not a big deal, but still :)

**Comment by lujun9972** [comment]
Yes, I got it. I will merge it. Thank you very much :)
 :+1:

**Comment by a13** [comment]
Thank you!

**Pull request merged**
